// frontend/src/components/settings/SettingsDialog.tsx
import { Check, RotateCcw } from "lucide-react";
import { Dialog } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Slider } from "@/components/ui/slider";
import { cn } from "@/lib/utils";
import {
  FONT_OPTIONS,
  THEME_OPTIONS,
  useSettings,
  type ThemeKey,
} from "@/store/settings";

interface SettingsDialogProps {
  open: boolean;
  onClose: () => void;
}

export function SettingsDialog({ open, onClose }: SettingsDialogProps) {
  const { settings, updateSettings, resetSettings } = useSettings();

  return (
    <Dialog
      open={open}
      onClose={onClose}
      title="设置"
      width="640px"
    >
      <div className="space-y-6">
        {/* 主题 */}
        <section>
          <h3 className="mb-1 text-xs font-semibold text-foreground">
            主题
          </h3>
          <p className="mb-3 text-[11px] text-muted-foreground">
            选择整体配色方案。「跟随系统」会按系统外观自动切换亮/暗。
          </p>
          <div className="grid grid-cols-3 gap-2.5">
            {THEME_OPTIONS.map((t) => {
              const active = settings.theme === t.key;
              return (
                <button
                  key={t.key}
                  onClick={() => updateSettings({ theme: t.key as ThemeKey })}
                  className={cn(
                    "group relative overflow-hidden rounded-lg border-2 p-3 text-left transition-all",
                    active
                      ? "border-primary"
                      : "border-border hover:border-primary/40"
                  )}
                >
                  {/* 预览色板 */}
                  <div
                    className="mb-2 flex h-12 items-center justify-center rounded-md border border-border/50"
                    style={{ background: t.swatch.bg }}
                  >
                    <div
                      className="rounded px-1.5 py-0.5 text-[10px] font-medium"
                      style={{
                        background: t.swatch.accent,
                        color: t.swatch.fg,
                      }}
                    >
                      Aa
                    </div>
                  </div>
                  <div className="flex items-center justify-between">
                    <div>
                      <div className="text-xs font-medium">{t.name}</div>
                      <div className="mt-0.5 text-[10px] text-muted-foreground">
                        {t.description}
                      </div>
                    </div>
                    {active && (
                      <Check className="h-3.5 w-3.5 shrink-0 text-primary" />
                    )}
                  </div>
                </button>
              );
            })}
          </div>
        </section>

        {/* 字体类型 */}
        <section>
          <h3 className="mb-1 text-xs font-semibold">字体类型</h3>
          <p className="mb-2 text-[11px] text-muted-foreground">
            字体立刻应用到全局。等宽字体更适合命令行场景。
          </p>
          <select
            value={settings.fontFamily}
            onChange={(e) => updateSettings({ fontFamily: e.target.value })}
            className="w-full rounded-md border border-input bg-background px-3 py-2 text-xs outline-none focus:border-primary"
          >
            {FONT_OPTIONS.map((f) => (
              <option key={f.label} value={f.value}>
                {f.label}
              </option>
            ))}
          </select>
        </section>

        {/* 字号 */}
        <section>
          <div className="mb-1 flex items-center justify-between">
            <h3 className="text-xs font-semibold">字体大小</h3>
            <span className="text-[11px] tabular-nums text-muted-foreground">
              {settings.fontSize}px
            </span>
          </div>
          <p className="mb-2 text-[11px] text-muted-foreground">
            调整全局字号。建议 12~14。
          </p>
          <Slider
            value={settings.fontSize}
            min={10}
            max={18}
            step={1}
            onChange={(v) => updateSettings({ fontSize: v })}
          />
          <div className="mt-1 flex justify-between text-[10px] text-muted-foreground">
            <span>10px</span>
            <span>14px</span>
            <span>18px</span>
          </div>
        </section>

        {/* 页面缩放 */}
        <section>
          <div className="mb-1 flex items-center justify-between">
            <h3 className="text-xs font-semibold">页面缩放</h3>
            <span className="text-[11px] tabular-nums text-muted-foreground">
              {settings.zoom}%
            </span>
          </div>
          <p className="mb-2 text-[11px] text-muted-foreground">
            整体缩放所有 UI 元素（含图表）。
          </p>
          <Slider
            value={settings.zoom}
            min={80}
            max={140}
            step={5}
            onChange={(v) => updateSettings({ zoom: v })}
          />
          <div className="mt-1 flex justify-between text-[10px] text-muted-foreground">
            <span>80%</span>
            <span>100%</span>
            <span>140%</span>
          </div>
        </section>

        {/* 操作 */}
        <div className="flex items-center justify-between border-t border-border pt-4">
          <Button
            variant="ghost"
            size="sm"
            className="h-8 gap-1.5 text-xs"
            onClick={() => resetSettings()}
          >
            <RotateCcw className="h-3 w-3" />
            恢复默认
          </Button>
          <Button
            size="sm"
            className="h-8 text-xs"
            onClick={onClose}
          >
            完成
          </Button>
        </div>
      </div>
    </Dialog>
  );
}

// frontend/src/components/SettingsDialog.vue
<template>
  <el-dialog
    :model-value="modelValue"
    title="设置"
    width="560px"
    destroy-on-close
    class="settings-dialog"
    @update:model-value="emit('update:modelValue', $event)"
  >
    <div class="settings-body">
      <!-- 主题 -->
      <section class="settings-section">
        <h3 class="sec-title">主题</h3>
        <p class="sec-desc">选择整体配色。「跟随系统」会按系统外观自动切换。</p>
        <div class="theme-grid">
          <button
            v-for="t in THEME_OPTIONS"
            :key="t.key"
            type="button"
            class="theme-card"
            :class="{ active: settings.theme === t.key }"
            @click="settings.setTheme(t.key)"
          >
            <div
              class="theme-swatch"
              :style="{ background: t.swatch.bg }"
            >
              <span
                class="theme-aa"
                :style="{
                  background: t.swatch.accent,
                  color: t.swatch.fg === '#888' ? '#fff' : t.swatch.fg,
                }"
              >
                Aa
              </span>
            </div>
            <div class="theme-meta">
              <div class="theme-name">{{ t.name }}</div>
              <div class="theme-desc">{{ t.description }}</div>
            </div>
            <el-icon v-if="settings.theme === t.key" class="theme-check">
              <Check />
            </el-icon>
          </button>
        </div>
      </section>

      <!-- 界面字体 -->
      <section class="settings-section">
        <h3 class="sec-title">界面字体</h3>
        <p class="sec-desc">字体立刻应用到全局 UI（菜单、表格、表单等）。</p>
        <el-select
          :model-value="settings.fontFamily"
          style="width: 100%"
          @change="(v: string) => settings.setFontFamily(v)"
        >
          <el-option
            v-for="f in FONT_OPTIONS"
            :key="f.label"
            :label="f.label"
            :value="f.value"
          >
            <span :style="{ fontFamily: f.value }">{{ f.label }}</span>
          </el-option>
        </el-select>
      </section>

      <!-- 界面字号 -->
      <section class="settings-section">
        <div class="sec-row">
          <h3 class="sec-title">界面字号</h3>
          <span class="sec-value">{{ settings.fontSize }} px</span>
        </div>
        <p class="sec-desc">建议 12～14。范围 11～20。</p>
        <el-slider
          :model-value="settings.fontSize"
          :min="11"
          :max="20"
          :step="1"
          show-stops
          @update:model-value="onFontSize"
        />
        <div class="preview-box" :style="uiPreviewStyle">
          预览：主机列表 · 概览 · CPU 32.5% · root@server
        </div>
      </section>

      <!-- 终端字体 -->
      <section class="settings-section">
        <h3 class="sec-title">终端字体</h3>
        <p class="sec-desc">仅影响「终端」标签页中的 xterm 显示。</p>
        <el-select
          :model-value="settings.terminalFontFamily"
          style="width: 100%"
          @change="(v: string) => settings.setTerminalFontFamily(v)"
        >
          <el-option
            v-for="f in TERMINAL_FONT_OPTIONS"
            :key="f.label"
            :label="f.label"
            :value="f.value"
          />
        </el-select>
      </section>

      <!-- 终端字号 -->
      <section class="settings-section">
        <div class="sec-row">
          <h3 class="sec-title">终端字号</h3>
          <span class="sec-value">{{ settings.terminalFontSize }} px</span>
        </div>
        <p class="sec-desc">建议 12～14。范围 10～22。</p>
        <el-slider
          :model-value="settings.terminalFontSize"
          :min="10"
          :max="22"
          :step="1"
          show-stops
          @update:model-value="onTermFontSize"
        />
        <div class="preview-box preview-box--term" :style="termPreviewStyle">
          root@host:~$ ls -la /var/log
        </div>
      </section>
    </div>

    <template #footer>
      <el-button @click="settings.resetSettings()">恢复默认</el-button>
      <el-button type="primary" @click="emit('update:modelValue', false)">
        完成
      </el-button>
    </template>
  </el-dialog>
</template>

<script setup lang="ts">
import { computed } from "vue";
import { Check } from "@element-plus/icons-vue";
import {
  FONT_OPTIONS,
  TERMINAL_FONT_OPTIONS,
  THEME_OPTIONS,
  useSettingsStore,
} from "@/stores/settings";

defineProps<{ modelValue: boolean }>();
const emit = defineEmits<{ "update:modelValue": [boolean] }>();

const settings = useSettingsStore();

const uiPreviewStyle = computed(() => ({
  fontFamily: settings.fontFamily,
  fontSize: `${settings.fontSize}px`,
}));

const termPreviewStyle = computed(() => ({
  fontFamily:
    settings.terminalFontFamily === "inherit"
      ? settings.fontFamily
      : settings.terminalFontFamily,
  fontSize: `${settings.terminalFontSize}px`,
}));

function onFontSize(v: number | number[]) {
  const n = Array.isArray(v) ? v[0] : v;
  settings.setFontSize(n);
}

function onTermFontSize(v: number | number[]) {
  const n = Array.isArray(v) ? v[0] : v;
  settings.setTerminalFontSize(n);
}
</script>

<style scoped lang="scss">
.settings-body {
  display: flex;
  flex-direction: column;
  gap: 20px;
  max-height: min(70vh, 560px);
  overflow-y: auto;
  padding-right: 4px;
}

.settings-section {
  min-width: 0;
}

.sec-title {
  margin: 0;
  font-size: 13px;
  font-weight: 600;
  color: var(--el-text-color-primary);
}

.sec-desc {
  margin: 4px 0 10px;
  font-size: 12px;
  color: var(--el-text-color-secondary);
  line-height: 1.45;
}

.sec-row {
  display: flex;
  align-items: baseline;
  justify-content: space-between;
  gap: 8px;
}

.sec-value {
  font-size: 12px;
  font-variant-numeric: tabular-nums;
  color: var(--el-text-color-secondary);
}

.theme-grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 10px;
}

.theme-card {
  position: relative;
  display: flex;
  flex-direction: column;
  gap: 8px;
  padding: 10px;
  border: 1px solid var(--el-border-color);
  border-radius: 8px;
  background: var(--el-bg-color);
  text-align: left;
  cursor: pointer;
  transition: border-color 0.15s, box-shadow 0.15s;

  &:hover {
    border-color: var(--el-color-primary-light-5);
  }
  &.active {
    border-color: var(--el-color-primary);
    box-shadow: 0 0 0 1px var(--el-color-primary);
  }
}

.theme-swatch {
  height: 48px;
  border-radius: 6px;
  border: 1px solid var(--el-border-color-lighter);
  display: flex;
  align-items: center;
  justify-content: center;
}

.theme-aa {
  padding: 2px 8px;
  border-radius: 4px;
  font-size: 11px;
  font-weight: 600;
}

.theme-name {
  font-size: 12px;
  font-weight: 600;
}

.theme-desc {
  margin-top: 2px;
  font-size: 11px;
  color: var(--el-text-color-secondary);
  line-height: 1.35;
}

.theme-check {
  position: absolute;
  top: 8px;
  right: 8px;
  color: var(--el-color-primary);
  font-size: 16px;
}

.preview-box {
  margin-top: 10px;
  padding: 10px 12px;
  border-radius: 6px;
  border: 1px dashed var(--el-border-color);
  background: var(--el-fill-color-lighter);
  color: var(--el-text-color-regular);
  line-height: 1.5;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;

  &--term {
    background: #0d0d0d;
    color: #d1d5db;
    border-color: #2a2a2a;
    font-variant-numeric: tabular-nums;
  }
}
</style>
