// frontend/src/react/components/file-preview-drawer.tsx
import { useEffect, useMemo, useState } from "react";
import { api, type filetext } from "@/api";
import { HighlightPane } from "@/react/components/local/highlight-pane";
import { Button } from "@/react/components/ui/button";
import { highlightFileHtml } from "@/utils/codeHighlight";
import { formatErr, splitTextLines } from "@/utils/format";

type OpenTarget = { path: string; name: string };

type Props = {
  host: string;
  target: OpenTarget | null;
  /** local：本机文件；默认读远程主机 */
  source?: "remote" | "local";
  onClose: () => void;
};

export function FilePreviewDrawer({ host, target, source = "remote", onClose }: Props) {
  const [preview, setPreview] = useState<filetext.Preview | null>(null);
  const [loading, setLoading] = useState(false);
  const [converting, setConverting] = useState(false);
  const [confirmNormalize, setConfirmNormalize] = useState(false);
  const [error, setError] = useState("");

  const open = !!target;
  const path = target?.path || "";
  const needsNormalize = !!preview?.needsNormalize && !!path;
  const lineCount = preview ? splitTextLines(preview.content ?? "").length : 0;
  const html = useMemo(
    () => highlightFileHtml(preview?.content || "", path || preview?.name || ""),
    [preview?.content, preview?.name, path],
  );

  useEffect(() => {
    if (!target) {
      setPreview(null);
      setError("");
      setConfirmNormalize(false);
      return;
    }
    let cancelled = false;
    setLoading(true);
    setError("");
    setConfirmNormalize(false);
    setPreview({
      path: target.path,
      name: target.name,
      content: "",
      encoding: "—",
      lineEnding: "—",
      needsNormalize: false,
      size: 0,
    });
    const read =
      source === "local"
        ? api.readLocalFilePreview(target.path)
        : api.readFilePreview(host, target.path);
    void read
      .then((result) => {
        if (cancelled) return;
        setPreview(result);
      })
      .catch((err) => {
        if (cancelled) return;
        setError(formatErr(err));
        setPreview({
          path: target.path,
          name: target.name,
          content: `读取失败: ${formatErr(err)}`,
          encoding: "—",
          lineEnding: "—",
          needsNormalize: false,
          size: 0,
        });
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [host, source, target]);

  async function normalizeToLinux() {
    if (!path || converting) return;
    if (!confirmNormalize) {
      setConfirmNormalize(true);
      return;
    }
    setConverting(true);
    setError("");
    try {
      const result =
        source === "local"
          ? await api.normalizeLocalFileToLinux(path)
          : await api.normalizeFileToLinux(host, path);
      setPreview(result);
      setConfirmNormalize(false);
    } catch (err) {
      setError(`转换失败: ${formatErr(err)}`);
    } finally {
      setConverting(false);
    }
  }

  if (!open) return null;

  return (
    <div className="fixed inset-0 z-40 flex justify-end">
      <button
        type="button"
        className="absolute inset-0 bg-black/55"
        aria-label="关闭预览"
        onClick={onClose}
      />
      <aside className="relative z-10 flex h-full w-1/2 min-w-[320px] flex-col border-l border-line bg-surface shadow-[0_8px_24px_rgba(0,0,0,0.45)]">
        <div className="flex h-12 shrink-0 items-center gap-2 border-b border-line px-4">
          <h2 className="min-w-0 flex-1 truncate text-sm font-medium text-ink">
            {preview?.name || target?.name || "预览"}
          </h2>
          <Button size="sm" onClick={onClose}>
            关闭
          </Button>
        </div>
        <div className="flex min-h-0 flex-1 flex-col p-3">
          {needsNormalize ? (
            <div className="mb-2 flex flex-wrap items-center justify-between gap-2 rounded-surface border border-warn/40 bg-warn/10 px-3 py-2 text-sm text-warn">
              <span>
                当前不是 Linux 标准格式（期望 UTF-8 + LF）：编码{" "}
                <strong>{preview?.encoding || "—"}</strong>，换行{" "}
                <strong>{preview?.lineEnding || "—"}</strong>。
                {confirmNormalize ? " 写前会备份为「原文件名.bak.时间戳」。确认转换？" : ""}
              </span>
              <div className="flex gap-2">
                {confirmNormalize ? (
                  <Button
                    size="sm"
                    onClick={() => {
                      setConfirmNormalize(false);
                    }}
                  >
                    取消
                  </Button>
                ) : null}
                <Button
                  size="sm"
                  variant="primary"
                  disabled={converting}
                  onClick={() => void normalizeToLinux()}
                >
                  {converting
                    ? "转换中…"
                    : confirmNormalize
                      ? "转换并保存"
                      : "转换为 UTF-8 / LF"}
                </Button>
              </div>
            </div>
          ) : null}
          {error ? <p className="mb-2 text-sm text-danger">{error}</p> : null}
          <div className="min-h-0 flex-1 overflow-hidden rounded-surface border border-line bg-graphite">
            {loading ? (
              <pre className="p-4 font-mono text-sm text-graphite-text">加载中…</pre>
            ) : (
              <HighlightPane html={html} text={preview?.content || ""} />
            )}
          </div>
          <div className="mt-2 flex shrink-0 items-center justify-between gap-4 text-[11px] text-muted">
            <span>{preview ? `${lineCount} 行` : ""}</span>
            <span className="inline-flex items-center gap-2 tabular-nums">
              <span className={needsNormalize ? "font-semibold text-danger" : "text-ink"}>
                {preview?.encoding || "—"}
              </span>
              <span>|</span>
              <span className={needsNormalize ? "font-semibold text-danger" : "text-ink"}>
                {preview?.lineEnding || "—"}
              </span>
            </span>
          </div>
        </div>
      </aside>
    </div>
  );
}

// frontend/src/components/files/FilePreviewDrawer.vue
<template>
  <!-- 文本预览抽屉：行号 + 底部编码/换行符 + Linux 标准转换 -->
  <el-drawer
    v-model="previewOpen"
    :title="preview?.name || '预览'"
    size="50%"
    destroy-on-close
    class="preview-drawer"
  >
    <div v-loading="previewLoading || previewConverting" class="preview-shell">
      <el-alert
        v-if="previewNeedsNormalize"
        type="warning"
        :closable="false"
        show-icon
        class="preview-normalize-alert"
      >
        <template #title>
          <div class="normalize-alert-body">
            <span>
              当前不是 Linux 标准格式（期望
              <strong>UTF-8 + LF</strong>）：编码
              <strong>{{ previewEncoding }}</strong>，换行
              <strong>{{ previewLineEnding }}</strong>。
            </span>
            <el-button
              type="primary"
              size="small"
              :loading="previewConverting"
              @click="onNormalizeToLinux"
            >
              转换为 UTF-8 / LF
            </el-button>
          </div>
        </template>
      </el-alert>
      <div class="preview-code" role="region" aria-label="文件预览">
        <CodePane
          v-if="!previewLoading && previewHtml"
          :html="previewHtml"
          :text="preview?.content || ''"
          searchable
        />
        <div v-else-if="!previewLoading && !previewHtml" class="preview-empty">
          (空文件)
        </div>
      </div>
      <div class="preview-status">
        <span class="status-left">{{ previewLineCountLabel }}</span>
        <span class="status-right">
          <span
            class="status-item"
            :class="{ 'is-warn': previewNeedsNormalize }"
            v-tip="'文件编码'"
          >{{ previewEncoding }}</span>
          <span class="status-sep">|</span>
          <span
            class="status-item"
            :class="{ 'is-warn': previewNeedsNormalize }"
            v-tip="'换行符'"
          >{{ previewLineEnding }}</span>
          <template v-if="previewNeedsNormalize">
            <span class="status-sep">|</span>
            <el-button
              link
              type="warning"
              size="small"
              :loading="previewConverting"
              @click="onNormalizeToLinux"
            >
              转 Linux 标准
            </el-button>
          </template>
        </span>
      </div>
    </div>
  </el-drawer>
</template>

<script setup lang="ts">
/**
 * 远程文本文件预览抽屉。
 * 父组件通过 openFile({path, name}) 打开；读取、转换 Linux 标准格式均在此完成。
 */
import { computed, ref } from "vue";
import { ElMessage, ElMessageBox } from "element-plus";
import { api } from "@/api";
import type { filetext } from "@/api";
import CodePane from "@/components/CodePane.vue";
import { highlightFileHtml } from "@/utils/codeHighlight";
import { splitTextLines } from "@/utils/format";

const props = defineProps<{ host: string }>();

const previewOpen = ref(false);
const preview = ref<filetext.Preview | null>(null);
const previewPath = ref("");
const previewLoading = ref(false);
const previewConverting = ref(false);

const previewLines = computed(() => {
  if (!preview.value) return [];
  return splitTextLines(preview.value.content ?? "");
});
const previewHtml = computed(() => {
  const text = preview.value?.content ?? "";
  if (!text) return "";
  const path = preview.value?.path || previewPath.value || preview.value?.name || "";
  return highlightFileHtml(text, path);
});
const previewEncoding = computed(() => preview.value?.encoding || "—");
const previewLineEnding = computed(() => preview.value?.lineEnding || "—");
const previewNeedsNormalize = computed(
  () => !!preview.value?.needsNormalize && !!previewPath.value
);
const previewLineCountLabel = computed(() => {
  const n = previewLines.value.length;
  if (!preview.value) return "";
  return `${n} 行`;
});

async function openFile(row: { path: string; name: string }) {
  previewOpen.value = true;
  previewPath.value = row.path;
  preview.value = {
    path: row.path,
    name: row.name,
    content: "",
    encoding: "—",
    lineEnding: "—",
    needsNormalize: false,
    size: 0,
  } as filetext.Preview;
  previewLoading.value = true;
  try {
    const p = await api.readFilePreview(props.host, row.path);
    preview.value = p;
    previewPath.value = p.path || row.path;
  } catch (e) {
    preview.value = {
      path: row.path,
      name: row.name,
      content: `读取失败: ${e}`,
      encoding: "—",
      lineEnding: "—",
      needsNormalize: false,
      size: 0,
    } as filetext.Preview;
  } finally {
    previewLoading.value = false;
  }
}

async function onNormalizeToLinux() {
  if (!previewPath.value || previewConverting.value) return;
  try {
    await ElMessageBox.confirm(
      `将把远程文件转换为 UTF-8 编码 + LF 换行（Linux 标准）。\n写前会备份为「原文件名.bak.时间戳」。\n\n${previewPath.value}`,
      "转换为 Linux 标准格式",
      {
        type: "warning",
        confirmButtonText: "转换并保存",
        cancelButtonText: "取消",
      }
    );
  } catch {
    return;
  }
  previewConverting.value = true;
  try {
    const p = await api.normalizeFileToLinux(props.host, previewPath.value);
    preview.value = p;
    previewPath.value = p.path || previewPath.value;
    ElMessage.success("已转换为 UTF-8 / LF，原文件已备份");
  } catch (e) {
    ElMessage.error(`转换失败: ${e}`);
  } finally {
    previewConverting.value = false;
  }
}

defineExpose({ openFile });
</script>

<style scoped lang="scss">
/* 预览：行号 + 底部状态栏 */
.preview-shell {
  display: flex;
  flex-direction: column;
  height: 100%;
  min-height: 0;
  border-radius: var(--m3-shape-m, 12px);
  overflow: hidden;
  background: #131316;
  color: #e6e0e9;
}
.preview-code {
  flex: 1;
  min-height: 0;
  display: flex;
  flex-direction: column;
  overflow: hidden;
}
.preview-line {
  display: flex;
  align-items: flex-start;
  min-height: 1.55em;
  padding: 0;
}
.preview-line:hover {
  background: rgba(255, 255, 255, 0.04);
}
.line-no {
  flex: 0 0 52px;
  width: 52px;
  padding: 0 10px 0 8px;
  text-align: right;
  color: #6b7280;
  user-select: none;
  border-right: 1px solid #2a2a2a;
}
.line-text {
  flex: 1;
  min-width: 0;
  padding: 0 12px 0 12px;
  white-space: pre-wrap;
  word-break: break-all;
  color: #e4e4e7;
}
.preview-empty {
  padding: 24px;
  text-align: center;
  color: #9ca3af;
  font-size: 12px;
}
.preview-normalize-alert {
  flex-shrink: 0;
  margin-bottom: 8px;
}
.normalize-alert-body {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  flex-wrap: wrap;
  width: 100%;
  font-size: 12px;
  line-height: 1.5;
}
.preview-status {
  flex-shrink: 0;
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
  min-height: 28px;
  padding: 4px 12px;
  font-size: 11px;
  color: #9ca3af;
  background: #161616;
  border-top: 1px solid #2a2a2a;
}
.status-left {
  min-width: 0;
}
.status-right {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  margin-left: auto;
  font-variant-numeric: tabular-nums;
}
.status-item {
  color: #e6e0e9;
  &.is-warn {
    color: #ffd8e4;
    font-weight: 600;
  }
}
.status-sep {
  color: #938f99;
}
</style>

<style lang="scss">
/* drawer body 撑满以便预览区占高（drawer 为组件根节点，scoped :deep 不可靠，用全局按类名限定） */
.preview-drawer .el-drawer__body {
  display: flex;
  flex-direction: column;
  padding: 12px 16px 16px;
  overflow: hidden;
}
</style>
